### ISSUE TITLE
SEGFAULT when using SetParameterLowerBound/SetParameterUpperBound

### ISSUE THREAD

**Issue by RiverIntheSky** [ceres-solver/ceres-solver#367]
backtrace
```
Thread 7 "ev" received signal SIGSEGV, Segmentation fault.
0x0000000000673b10 in void Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >, Eigen::internal::assign_op<double> >(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > const&, Eigen::internal::assign_op<double> const&) ()
(gdb) bt
#0  0x0000000000673b10 in void Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >, Eigen::internal::assign_op<double> >(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > const&, Eigen::internal::assign_op<double> const&) ()
#1  0x00000000007422e3 in ceres::internal::FindInterpolatingPolynomial(std::vector<ceres::internal::FunctionSample, std::allocator<ceres::internal::FunctionSample> > const&) ()
#2  0x000000000074432e in ceres::internal::MinimizeInterpolatingPolynomial(std::vector<ceres::internal::FunctionSample, std::allocator<ceres::internal::FunctionSample> > const&, double, double, double*, double*) ()
#3  0x000000000073437e in ceres::internal::LineSearch::InterpolatingPolynomialMinimizingStepSize(ceres::LineSearchInterpolationType const&, ceres::internal::FunctionSample const&, ceres::internal::FunctionSample const&, ceres::internal::FunctionSample const&, double, double) const ()
#4  0x0000000000735978 in ceres::internal::ArmijoLineSearch::DoSearch(double, double, double, ceres::internal::LineSearch::Summary*) const ()
#5  0x0000000000734043 in ceres::internal::LineSearch::Search(double, double, double, ceres::internal::LineSearch::Summary*) const ()
#6  0x0000000000708a20 in ceres::internal::TrustRegionMinimizer::DoLineSearch(Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, double, Eigen::Matrix<double, -1, 1, 0, -1, 1>*) ()
#7  0x000000000070cdf9 in ceres::internal::TrustRegionMinimizer::Minimize(ceres::internal::Minimizer::Options const&, double*, ceres::Solver::Summary*) ()
#8  0x00000000006e0f81 in ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
#9  0x00000000006e1649 in ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
...
```
I couldn't figure out if it's cere's problem of using Eigen, or there is some problem with my cost function that line search couldn't find a valid step size. My cost function is discontinous and I approximated the jacobian myself.
Any help would be appreciated!

Eigen  3.2.92
ubuntu 16.04
gcc 5.4.0

**Comment by sandwichmaker** [comment]
This seems odd and unexpected. Can you run the solver with -logtostderr -v=3 and share the log here? I'd like to see the polynomial thats actually causing this mess.

**Comment by sandwichmaker** [comment]
ping? if I do not hear back I will close this as unreproducible.

**Comment by sandwichmaker** [comment]
or rather, I am going to close this, please update/re-open if you have feedback.
