### ISSUE TITLE
Docs dependency: ImportError: No module named sphinx_rtd_theme

### ISSUE THREAD

**Issue by deysumitkr** [ceres-solver/ceres-solver#626]
On building the docs:
```
Running Sphinx v1.6.7
making output directory...

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/sdey/.local/lib/python2.7/site-packages/six.py", line 719, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 102, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme

[  2%] Built target ceres_docs
```

Maybe be [this dependency on sphinx_rtd_theme](https://github.com/ceres-solver/ceres-solver/blob/7ef83e07592ead74eeacc227b642df1959d2a246/docs/source/conf.py#L102) can be checked beforehand.

**Comment by sandwichmaker** [comment]
Thats a good idea @deysumitkr do you want to add the check to cmake?

**Comment by deysumitkr** [comment]
Thanks @sandwichmaker. Yes, I would do that in next week.

**Comment by sandwichmaker** [comment]
ping?

**Comment by deysumitkr** [comment]
This has been resolved here: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/18620

**Comment by sandwichmaker** [comment]
Oh perfect, I am sorry I forgot that this had been fixed.
